#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/Neon
#    username: postgres
#    password: suffu7x
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
